use EXAM;
-- department
-- DEPT_ID, DEPT_NAME
CREATE TABLE DEPARTMENT (
	DEPT_ID VARCHAR(4) PRIMARY KEY, 
	DEPT_NAME VARCHAR(50) NOT NULL
);

-- student
-- STUDENT_ID, NAME, HEIGHT- NULL 허용, DEPT_ID(REFERENCE)
CREATE TABLE STUDENT (
STUDENT_ID CHAR(8) PRIMARY KEY, 
NAME VARCHAR(20) NOT NULL, 
HEIGHT DECIMAL(5,2), 
DEPT_ID VARCHAR(4), 
CONSTRAINT FK_STUDENT_DEPARTMENT foreign key(DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID)
);

-- professor
-- PROF_ID, PROF_NAME, DEPT_ID(REFERENCE)
CREATE TABLE PROFESSOR (
PROF_ID VARCHAR(4) PRIMARY KEY, 
PROF_NAME VARCHAR(20) NOT NULL, 
DEPT_ID VARCHAR(4),
CONSTRAINT FK_PROFESSOR_DEPARTMENT foreign key(DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID)
);

-- subject
-- SUBJ_ID, PROF_ID(REFERENCE),START_DATE,END_DATE,SUBJ_NAME 
CREATE TABLE SUBJECT (
SUBJ_ID VARCHAR(8) PRIMARY KEY, 
PROF_ID VARCHAR(4) ,
CONSTRAINT FK_SUBJECT_PROFESSOR foreign key(PROF_ID) REFERENCES PROFESSOR(PROF_ID), 
START_DATE DATE NOT NULL, 
END_DATE DATE NOT NULL, 
SUBJ_NAME VARCHAR(100) NOT NULL
);


-- enrollment
-- ENROLL_ID, STUDENT_ID(REFERENCE), SUBJ_ID(REFERENCE), ENROLL_DATE
CREATE TABLE ENROLLMENT (
ENROLL_ID INT AUTO_INCREMENT PRIMARY KEY, 
STUDENT_ID CHAR(8),
CONSTRAINT FK_ENROLLMENT_STUDENT foreign key (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID) , 
SUBJ_ID VARCHAR(8),
CONSTRAINT FK_ENROLLMENT_SUBJECT foreign key (SUBJ_ID) REFERENCES SUBJECT(SUBJ_ID), 
ENROLL_DATE DATE NOT NULL
);





INSERT INTO DEPARTMENT VALUES ('A001','데이터사이언스');
INSERT INTO DEPARTMENT VALUES ('A002','경영학과');
INSERT INTO STUDENT (STUDENT_ID, NAME, HEIGHT, DEPT_ID) VALUES ('20250001','홍길동',163.5,'A002');
INSERT INTO STUDENT (STUDENT_ID, NAME, DEPT_ID) VALUES ('20250002','성춘향','A001');
INSERT INTO PROFESSOR VALUES ('P001','김유진','A001');
INSERT INTO SUBJECT VALUES ('S001','P001','2025-03-01','2025-06-30','파이썬');
INSERT INTO ENROLLMENT (STUDENT_ID, SUBJ_ID, ENROLL_DATE)VALUES ( '20250001','S001',CURDATE());

select CURDATE(); -- FROM DUAL 생략가능

select LOWER('DO IT SQL'), UPPER ('do it sql');

